spring:
    profiles: local-int
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
   # enabling faster registration for this profile
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
      
---

spring:
    profiles: docker-demo
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://evss-ngen-poc-eurekaserver:8761/eureka/      
  # enabling faster registration for this profile
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 20      